### ISSUE TITLE
DLL load failed while importing rdBase on Windows with RDKit 2024.03.5

### ISSUE THREAD

**Issue by RMeli** [conda-forge/rdkit-feedstock#168]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

https://github.com/rdkit/rdkit/issues/7679

### Installed packages

```shell
# packages in environment at C:\Users\runneradmin\miniconda3\envs\spyrmsd:
#
# Name                    Version                   Build  Channel
black                     24.4.2          py310h5588dad_0    conda-forge
brotli                    1.1.0                hcfcfb64_1    conda-forge
brotli-bin                1.1.0                hcfcfb64_1    conda-forge
brotli-python             1.1.0           py310h00ffb61_1    conda-forge
bzip2                     1.0.8                h2466b09_7    conda-forge
ca-certificates           2024.7.4             h56e8100_0    conda-forge
cairo                     1.18.0               h32b962e_3    conda-forge
certifi                   2024.7.4           pyhd8ed1ab_0    conda-forge
cffi                      1.16.0          py310h8d17308_0    conda-forge
chardet                   5.2.0           py310h5588dad_1    conda-forge
charset-normalizer        3.3.2              pyhd8ed1ab_0    conda-forge
click                     8.1.7           win_pyh7428d3b_0    conda-forge
codecov                   2.1.13             pyhd8ed1ab_0    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
contourpy                 1.2.1           py310h232114e_0    conda-forge
coverage                  7.6.0           py310ha8f682b_0    conda-forge
cycler                    0.12.1             pyhd8ed1ab_0    conda-forge
exceptiongroup            1.2.2              pyhd8ed1ab_0    conda-forge
expat                     2.6.2                h63175ca_0    conda-forge
flake8                    7.1.0              pyhd8ed1ab_0    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 h77eed37_2    conda-forge
fontconfig                2.14.2               hbde0cde_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
fonttools                 4.53.1          py310ha8f682b_0    conda-forge
freetype                  2.12.1               hdaf720e_2    conda-forge
freetype-py               2.3.0              pyhd8ed1ab_0    conda-forge
greenlet                  3.0.3           py310h00ffb61_0    conda-forge
h2                        4.1.0              pyhd8ed1ab_0    conda-forge
openssl                   3.3.1                h2466b09_2    conda-forge
packaging                 24.1               pyhd8ed1ab_0    conda-forge
pandas                    2.2.2           py310hb4db72f_1    conda-forge
pathspec                  0.12.1             pyhd8ed1ab_0    conda-forge
pcre2                     10.44                h3d7b363_0    conda-forge
pebble                    5.0.7              pyhd8ed1ab_0    conda-forge
pillow                    10.4.0          py310h3e38d90_0    conda-forge
pip                       24.0               pyhd8ed1ab_0    conda-forge
pixman                    0.43.4               h63175ca_0    conda-forge
platformdirs              4.2.2              pyhd8ed1ab_0    conda-forge
pluggy                    1.5.0              pyhd8ed1ab_0    conda-forge
psutil                    6.0.0           py310ha8f682b_0    conda-forge
pthread-stubs             0.4               hcd874cb_1001    conda-forge
pthreads-win32            2.9.1                hfa6e2cd_3    conda-forge
py-cpuinfo                9.0.0              pyhd8ed1ab_0    conda-forge
pycairo                   1.26.1          py310hb6096a9_0    conda-forge
pycodestyle               2.12.0             pyhd8ed1ab_0    conda-forge
pycparser                 2.22               pyhd8ed1ab_0    conda-forge
pyflakes                  3.2.0              pyhd8ed1ab_0    conda-forge
pyparsing                 3.1.2              pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1              pyh0701188_6    conda-forge
pytest                    8.3.2              pyhd8ed1ab_0    conda-forge
pytest-benchmark          4.0.0              pyhd8ed1ab_0    conda-forge
pytest-cov                5.0.0              pyhd8ed1ab_0    conda-forge
python                    3.10.14         h4de0772_0_cpython    conda-forge
python-dateutil           2.9.0              pyhd8ed1ab_0    conda-forge
python-tzdata             2024.1             pyhd8ed1ab_0    conda-forge
python_abi                3.10                    4_cp310    conda-forge
pytz                      2024.1             pyhd8ed1ab_0    conda-forge
qhull                     2020.2               hc790b64_5    conda-forge
rdkit                     2024.03.5       py310h142e3df_2    conda-forge
reportlab                 4.2.2           py310ha8f682b_0    conda-forge
requests                  2.32.3             pyhd8ed1ab_0    conda-forge
rlpycairo                 0.2.0              pyhd8ed1ab_0    conda-forge
rustworkx                 0.15.1          py310hddca29c_0    conda-forge
scipy                     1.14.0          py310h46043a1_1    conda-forge
setuptools                71.0.4             pyhd8ed1ab_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
spyrmsd                   0.9.0.dev0               pypi_0    pypi
sqlalchemy                2.0.31          py310ha8f682b_0    conda-forge
tbb                       2021.12.0            hc790b64_3    conda-forge
tk                        8.6.13               h5226925_1    conda-forge
toml                      0.10.2             pyhd8ed1ab_0    conda-forge
tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
typing-extensions         4.12.2               hd8ed1ab_0    conda-forge
typing_extensions         4.12.2             pyha770c72_0    conda-forge
tzdata                    2024a                h0c530f3_0    conda-forge
ucrt                      10.0.22621.0         h57928b3_0    conda-forge
unicodedata2              15.1.0          py310h8d17308_0    conda-forge
urllib3                   2.2.2              pyhd8ed1ab_1    conda-forge
vc                        14.3                h8a93ad2_20    conda-forge
vc14_runtime              14.40.33810         ha82c5b3_20    conda-forge
vs2015_runtime            14.40.33810         h3bf8584_20    conda-forge
wheel                     0.43.0             pyhd8ed1ab_1    conda-forge
win_inet_pton             1.1.0              pyhd8ed1ab_6    conda-forge
xorg-libxau               1.0.11               hcd874cb_0    conda-forge
xorg-libxdmcp             1.1.3                hcd874cb_0    conda-forge
xz                        5.2.6                h8d14728_0    conda-forge
zlib                      1.3.1                h2466b09_1    conda-forge
zstandard                 0.23.0          py310he5e10e1_0    conda-forge
zstd                      1.5.6                h0ea2cb4_0    conda-forge
```

### Environment info

```shell
mamba version : 1.5.8
     active environment : spyrmsd
    active env location : C:\Users\runneradmin\miniconda3\envs\spyrmsd
            shell level : 1
       user config file : C:\Users\runneradmin\.condarc
 populated config files : C:\Users\runneradmin\miniconda3\.condarc
                          C:\Users\runneradmin\.condarc
          conda version : 24.3.0
    conda-build version : not installed
         python version : 3.10.14.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=x86_64_v3
                          __conda=24.3.0=0
                          __win=0=0
       base environment : C:\Users\runneradmin\miniconda3  (writable)
      conda av data dir : C:\Users\runneradmin\miniconda3\etc\conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/rdkit/win-64
                          https://conda.anaconda.org/rdkit/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\runneradmin\conda_pkgs_dir
       envs directories : C:\Users\runneradmin\miniconda3\envs
                          C:\Users\runneradmin\.conda\envs
                          C:\Users\runneradmin\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/24.3.0 requests/2.31.0 CPython/3.10.14 Windows/10 Windows/10.0.20348 solver/libmamba conda-libmamba-solver/24.1.0 libmambapy/1.5.8
          administrator : True
             netrc file : None
           offline mode : False
```

**Comment by greglandrum** [comment]
I can't reproduce this on my windows machine.
Here's output on a freshly installed rdkit environment on windows:
```
$ python 
Python 3.12.4 | packaged by conda-forge | (main, Jun 17 2024, 10:04:44) [MSC v.1940 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from rdkit import Chem
>>> import rdkit
>>> rdkit.__version__
'2024.03.5'
```

**Comment by EmPajak21** [comment]
Same issue here. Tried multiple fresh envs and versions of Python 3.8-3.10 - and could not get anything working except for a Python 3.8 env with pip install rdkit-pypi only on scripts, not .ipynb. 

Would be really grateful for any thoughts? 

![image_2024-08-02_144805105](https://github.com/user-attachments/assets/32c714e4-b1b2-4ae1-9465-ce134a8ce50b)

**Comment by greglandrum** [comment]
> Same issue here. Tried multiple fresh envs and versions of Python 3.8-3.10 

We need to see the contents of your environment.

Please do a "conda list" and then "python -c 'from rdkit import Chem'" and paste the entire contents of the output (including the commands) in as text

**Comment by EmPajak21** [comment]
Hi, thanks for your quick reply, please see attached:

(newenv) PS C:\Users\U10087775\Projects> conda list
# packages in environment at C:\Users\U10087775\AppData\Local\miniconda3\envs\newenv:
#
# Name                    Version                   Build  Channel
asttokens                 2.4.1              pyhd8ed1ab_0    conda-forge
blas                      1.0                         mkl
bottleneck                1.3.7            py39h9128911_0
brotli                    1.0.9                h2bbff1b_8
brotli-bin                1.0.9                h2bbff1b_8
bzip2                     1.0.8                h2bbff1b_6
ca-certificates           2024.7.4             h56e8100_0    conda-forge
cairo                     1.18.0               h1fef639_0    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
comm                      0.2.2              pyhd8ed1ab_0    conda-forge
contourpy                 1.2.0            py39h59b6b97_0
cycler                    0.11.0             pyhd3eb1b0_0
debugpy                   1.8.2            py39ha51f57c_0    conda-forge
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
exceptiongroup            1.2.2              pyhd8ed1ab_0    conda-forge
executing                 2.0.1              pyhd8ed1ab_0    conda-forge
expat                     2.6.2                hd77b12b_0
font-ttf-dejavu-sans-mono 2.37                 hd3eb1b0_0
font-ttf-inconsolata      2.001                hcb22688_0
font-ttf-source-code-pro  2.030                hd3eb1b0_0
font-ttf-ubuntu           0.83                 h8b1ccd4_0
fontconfig                2.14.2               hbde0cde_0    conda-forge
fonts-anaconda            1                    h8fa9717_0
fonts-conda-ecosystem     1                    hd3eb1b0_0
fonttools                 4.51.0           py39h2bbff1b_0
freetype                  2.12.1               ha860e81_0
glib                      2.78.4               hd77b12b_0
glib-tools                2.78.4               hd77b12b_0
greenlet                  3.0.1            py39hd77b12b_0
icu                       73.2                 h63175ca_0    conda-forge
importlib-metadata        8.2.0              pyha770c72_0    conda-forge
importlib_metadata        8.2.0                hd8ed1ab_0    conda-forge
importlib_resources       6.4.0            py39haa95532_0
intel-openmp              2023.1.0         h59b6b97_46320
ipykernel                 6.29.5             pyh4bbf305_0    conda-forge
ipython                   8.18.1             pyh7428d3b_3    conda-forge
jedi                      0.19.1             pyhd8ed1ab_0    conda-forge
jpeg                      9e                   h827c3e9_2
jupyter_client            8.6.2              pyhd8ed1ab_0    conda-forge
jupyter_core              5.7.2            py39hcbf5309_0    conda-forge
kiwisolver                1.4.4            py39hd77b12b_0
krb5                      1.21.3               hdf4eb48_0    conda-forge
lcms2                     2.12                 h83e58a3_0
lerc                      3.0                  hd77b12b_0
libboost                  1.84.0               hcc118f5_2    conda-forge
libboost-python           1.84.0           py39h8f1c5a3_5    conda-forge
libbrotlicommon           1.0.9                h2bbff1b_8
libbrotlidec              1.0.9                h2bbff1b_8
libbrotlienc              1.0.9                h2bbff1b_8
libdeflate                1.17                 h2bbff1b_1
libffi                    3.4.4                hd77b12b_1
libglib                   2.78.4               ha17d25a_0
libiconv                  1.17                 hcfcfb64_2    conda-forge
libpng                    1.6.39               h8cc25b3_0
libpq                     16.3                 hab9416b_0    conda-forge
librdkit                  2024.03.5            h4c5bbc8_2    conda-forge
libsodium                 1.0.18               h8d14728_1    conda-forge
libtiff                   4.5.1                hd77b12b_0
libwebp-base              1.3.2                h2bbff1b_0
libzlib                   1.2.13               h2466b09_6    conda-forge
lz4-c                     1.9.4                h2bbff1b_1
matplotlib-base           3.8.4            py39h4ed8f06_0
matplotlib-inline         0.1.7              pyhd8ed1ab_0    conda-forge
mkl                       2023.1.0         h6b88ed4_46358
mkl-service               2.4.0            py39h2bbff1b_1
mkl_fft                   1.3.8            py39h2bbff1b_0
mkl_random                1.2.4            py39h59b6b97_0
nest-asyncio              1.6.0              pyhd8ed1ab_0    conda-forge
numexpr                   2.8.7            py39h2cd9be0_0
numpy                     1.26.4           py39h055cbcc_0
numpy-base                1.26.4           py39h65a83cf_0
openjpeg                  2.4.0                h4afccc4_2
openssl                   3.3.1                h2466b09_2    conda-forge
packaging                 24.1             py39haa95532_0
pandas                    2.2.2            py39h5da7b33_0
parso                     0.8.4              pyhd8ed1ab_0    conda-forge
pcre2                     10.42                h0ff8eda_1
pickleshare               0.7.5                   py_1003    conda-forge
pip                       24.0             py39haa95532_0
pixman                    0.43.4               h63175ca_0    conda-forge
platformdirs              4.2.2              pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.47             pyha770c72_0    conda-forge
psutil                    6.0.0            py39ha55e580_0    conda-forge
pure_eval                 0.2.3              pyhd8ed1ab_0    conda-forge
pycairo                   1.23.0           py39had253c0_0
pygments                  2.18.0             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.9            py39haa95532_0
python                    3.9.19               h1aa4202_1
python-dateutil           2.9.0post0       py39haa95532_2
python-tzdata             2023.3             pyhd3eb1b0_0
python_abi                3.9                      2_cp39    conda-forge
pytz                      2024.1           py39haa95532_0
pywin32                   306              py39h99910a6_2    conda-forge
pyzmq                     26.0.3           py39h03e5c00_0    conda-forge
rdkit                     2024.03.5        py39h29728c6_2    conda-forge
reportlab                 3.5.67           py39h52c0f85_1
setuptools                69.5.1           py39haa95532_0
six                       1.16.0             pyhd3eb1b0_1
sqlalchemy                2.0.30           py39h827c3e9_0
sqlite                    3.45.3               h2bbff1b_0
stack_data                0.6.2              pyhd8ed1ab_0    conda-forge
tbb                       2021.8.0             h59b6b97_0
tornado                   6.4.1            py39ha55e580_0    conda-forge
traitlets                 5.14.3             pyhd8ed1ab_0    conda-forge
typing-extensions         4.11.0           py39haa95532_0
typing_extensions         4.11.0           py39haa95532_0
tzdata                    2024a                h04d1e81_0
ucrt                      10.0.20348.0         haa95532_0
unicodedata2              15.1.0           py39h2bbff1b_0
vc                        14.2                 h2eaa2aa_4
vc14_runtime              14.40.33810         ha82c5b3_20    conda-forge
vs2015_runtime            14.40.33810         h3bf8584_20    conda-forge
wcwidth                   0.2.13             pyhd8ed1ab_0    conda-forge
wheel                     0.43.0           py39haa95532_0
xz                        5.4.6                h8cc25b3_1
zeromq                    4.3.5                he1f189c_4    conda-forge
zipp                      3.17.0           py39haa95532_0
zlib                      1.2.13               h2466b09_6    conda-forge
zstd                      1.5.5                hd43e919_2
(newenv) PS C:\Users\U10087775\Projects> python -c 'from rdkit import Chem'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\U10087775\AppData\Local\miniconda3\envs\newenv\lib\site-packages\rdkit\__init__.py", line 6, in <module>
    from . import rdBase
ImportError: DLL load failed while importing rdBase: The specified module could not be found.

**Comment by greglandrum** [comment]
Thanks. I'm traveling this weekend , but will try to figure out what's going on on Monday

**Comment by skearnes** [comment]
I was able to reproduce in a clean conda environment; I'll look into the DLL listings.

**Comment by skearnes** [comment]
> DLL load failed while importing rdBase

I compared the DLL lists before and after #158 and the `bin/` list matches but the `lib/` list is missing in the new version:

```
2024-07-19T12:59:08.7654729Z ?rw-rw-rw- 0/0      94720 2024-07-19 12:27:01 Library/lib/RDKitAbbreviations.dll 
2024-07-19T12:59:08.7655848Z ?rw-rw-rw- 0/0      27136 2024-07-19 12:18:02 Library/lib/RDKitAlignment.dll 
2024-07-19T12:59:08.7656949Z ?rw-rw-rw- 0/0      47616 2024-07-19 12:33:09 Library/lib/RDKitAvalonLib.dll 
2024-07-19T12:59:08.7658063Z ?rw-rw-rw- 0/0     170496 2024-07-19 12:24:01 Library/lib/RDKitCIPLabeler.dll 
2024-07-19T12:59:08.7659180Z ?rw-rw-rw- 0/0      15360 2024-07-19 12:16:28 Library/lib/RDKitCatalogs.dll 
2024-07-19T12:59:08.7660417Z ?rw-rw-rw- 0/0     680960 2024-07-19 12:38:12 Library/lib/RDKitChemReactions.dll 
2024-07-19T12:59:08.7661621Z ?rw-rw-rw- 0/0     253952 2024-07-19 12:29:43 Library/lib/RDKitChemTransforms.dll 
2024-07-19T12:59:08.7662774Z ?rw-rw-rw- 0/0      29184 2024-07-19 12:18:49 Library/lib/RDKitChemicalFeatures.dll 
2024-07-19T12:59:08.7663935Z ?rw-rw-rw- 0/0     225792 2024-07-19 12:16:28 Library/lib/RDKitDataStructs.dll 
2024-07-19T12:59:08.7665069Z ?rw-rw-rw- 0/0     355328 2024-07-19 12:27:39 Library/lib/RDKitDepictor.dll 
2024-07-19T12:59:08.7666180Z ?rw-rw-rw- 0/0      54272 2024-07-19 12:40:52 Library/lib/RDKitDeprotect.dll 
2024-07-19T12:59:08.7667363Z ?rw-rw-rw- 0/0     676352 2024-07-19 12:35:56 Library/lib/RDKitDescriptors.dll 
2024-07-19T12:59:08.7668493Z ?rw-rw-rw- 0/0      96256 2024-07-19 12:36:06 Library/lib/RDKitDetermineBonds.dll 
2024-07-19T12:59:08.7669624Z ?rw-rw-rw- 0/0     269824 2024-07-19 12:32:28 Library/lib/RDKitDistGeomHelpers.dll 
2024-07-19T12:59:08.7670769Z ?rw-rw-rw- 0/0     138240 2024-07-19 12:31:22 Library/lib/RDKitDistGeometry.dll 
2024-07-19T12:59:08.7671945Z ?rw-rw-rw- 0/0     279552 2024-07-19 12:22:09 Library/lib/RDKitEHTLib.dll 
2024-07-19T12:59:08.7673050Z ?rw-rw-rw- 0/0      22528 2024-07-19 12:16:11 Library/lib/RDKitEigenSolvers.dll 
2024-07-19T12:59:08.7674290Z ?rw-rw-rw- 0/0     266752 2024-07-19 12:34:58 Library/lib/RDKitFMCS.dll 
2024-07-19T12:59:08.7675404Z ?rw-rw-rw- 0/0    1431040 2024-07-19 12:33:02 Library/lib/RDKitFileParsers.dll 
2024-07-19T12:59:08.7676545Z ?rw-rw-rw- 0/0     567808 2024-07-19 12:26:09 Library/lib/RDKitFilterCatalog.dll 
2024-07-19T12:59:08.7677703Z ?rw-rw-rw- 0/0     409088 2024-07-19 12:26:30 Library/lib/RDKitFingerprints.dll 
2024-07-19T12:59:08.7678848Z ?rw-rw-rw- 0/0     568832 2024-07-19 12:28:41 Library/lib/RDKitForceField.dll 
2024-07-19T12:59:08.7679972Z ?rw-rw-rw- 0/0     391680 2024-07-19 12:30:20 Library/lib/RDKitForceFieldHelpers.dll 
2024-07-19T12:59:08.7681979Z ?rw-rw-rw- 0/0     143360 2024-07-19 12:26:47 Library/lib/RDKitFragCatalog.dll 
2024-07-19T12:59:08.7683208Z ?rw-rw-rw- 0/0      51200 2024-07-19 12:21:57 Library/lib/RDKitFreeSASALib.dll 
2024-07-19T12:59:08.7684399Z ?rw-rw-rw- 0/0     185344 2024-07-19 12:46:34 Library/lib/RDKitGeneralizedSubstruct.dll 
2024-07-19T12:59:08.7685558Z ?rw-rw-rw- 0/0      94208 2024-07-19 12:21:34 Library/lib/RDKitGenericGroups.dll 
2024-07-19T12:59:08.7686681Z ?rw-rw-rw- 0/0    1556992 2024-07-19 12:21:26 Library/lib/RDKitGraphMol.dll 
2024-07-19T12:59:08.7687774Z ?rw-rw-rw- 0/0    1139712 2024-07-19 12:14:21 Library/lib/RDKitInchi.dll 
2024-07-19T12:59:08.7688947Z ?rw-rw-rw- 0/0      58880 2024-07-19 12:17:36 Library/lib/RDKitInfoTheory.dll 
2024-07-19T12:59:08.7690048Z ?rw-rw-rw- 0/0      68608 2024-07-19 12:35:11 Library/lib/RDKitMMPA.dll 
2024-07-19T12:59:08.7691157Z ?rw-rw-rw- 0/0     554496 2024-07-19 12:38:48 Library/lib/RDKitMarvinParser.dll 
2024-07-19T12:59:08.7692275Z ?rw-rw-rw- 0/0      63488 2024-07-19 12:25:08 Library/lib/RDKitMolAlign.dll 
2024-07-19T12:59:08.7693380Z ?rw-rw-rw- 0/0      41472 2024-07-19 12:22:37 Library/lib/RDKitMolCatalog.dll 
2024-07-19T12:59:08.7694504Z ?rw-rw-rw- 0/0     136704 2024-07-19 12:26:55 Library/lib/RDKitMolChemicalFeatures.dll 
2024-07-19T12:59:08.7695764Z ?rw-rw-rw- 0/0     935936 2024-07-19 12:41:08 Library/lib/RDKitMolDraw2D.dll 
2024-07-19T12:59:08.7696995Z ?rw-rw-rw- 0/0     223232 2024-07-19 12:41:18 Library/lib/RDKitMolEnumerator.dll 
2024-07-19T12:59:08.7698115Z ?rw-rw-rw- 0/0      73216 2024-07-19 12:37:24 Library/lib/RDKitMolHash.dll 
2024-07-19T12:59:08.7699219Z ?rw-rw-rw- 0/0     297472 2024-07-19 12:22:59 Library/lib/RDKitMolInterchange.dll 
2024-07-19T12:59:08.7700369Z ?rw-rw-rw- 0/0     555008 2024-07-19 12:40:42 Library/lib/RDKitMolStandardize.dll 
2024-07-19T12:59:08.7701495Z ?rw-rw-rw- 0/0      82944 2024-07-19 12:21:43 Library/lib/RDKitMolTransforms.dll 
2024-07-19T12:59:08.7702682Z ?rw-rw-rw- 0/0     131584 2024-07-19 12:31:51 Library/lib/RDKitO3AAlign.dll 
2024-07-19T12:59:08.7703894Z ?rw-rw-rw- 0/0       9728 2024-07-19 12:24:35 Library/lib/RDKitOptimizer.dll 
2024-07-19T12:59:08.7705020Z ?rw-rw-rw- 0/0      72192 2024-07-19 12:22:33 Library/lib/RDKitPartialCharges.dll 
2024-07-19T12:59:08.7706135Z ?rw-rw-rw- 0/0      33280 2024-07-19 12:16:19 Library/lib/RDKitRDBoost.dll 
2024-07-19T12:59:08.7707317Z ?rw-rw-rw- 0/0     206848 2024-07-19 12:15:22 Library/lib/RDKitRDGeneral.dll 
2024-07-19T12:59:08.7708507Z ?rw-rw-rw- 0/0     103424 2024-07-19 12:17:09 Library/lib/RDKitRDGeometryLib.dll 
2024-07-19T12:59:08.7709699Z ?rw-rw-rw- 0/0      84480 2024-07-19 12:29:33 Library/lib/RDKitRDInchiLib.dll 
2024-07-19T12:59:08.7710807Z ?rw-rw-rw- 0/0      89600 2024-07-19 12:16:03 Library/lib/RDKitRDStreams.dll 
2024-07-19T12:59:08.7711924Z ?rw-rw-rw- 0/0     502272 2024-07-19 12:47:34 Library/lib/RDKitRGroupDecomposition.dll 
2024-07-19T12:59:08.7713064Z ?rw-rw-rw- 0/0     294400 2024-07-19 12:36:13 Library/lib/RDKitRascalMCES.dll 
2024-07-19T12:59:08.7714191Z ?rw-rw-rw- 0/0      57344 2024-07-19 12:26:55 Library/lib/RDKitReducedGraphs.dll 
2024-07-19T12:59:08.7715322Z ?rw-rw-rw- 0/0      78848 2024-07-19 12:15:09 Library/lib/RDKitRingDecomposerLib.dll 
2024-07-19T12:59:08.7716542Z ?rw-rw-rw- 0/0     226304 2024-07-19 12:23:24 Library/lib/RDKitSLNParse.dll 
2024-07-19T12:59:08.7717772Z ?rw-rw-rw- 0/0     116224 2024-07-19 12:45:17 Library/lib/RDKitScaffoldNetwork.dll 
2024-07-19T12:59:08.7718909Z ?rw-rw-rw- 0/0      32256 2024-07-19 12:24:22 Library/lib/RDKitShapeHelpers.dll 
2024-07-19T12:59:08.7720094Z ?rw-rw-rw- 0/0      32768 2024-07-19 12:16:34 Library/lib/RDKitSimDivPickers.dll 
2024-07-19T12:59:08.7721213Z ?rw-rw-rw- 0/0     500224 2024-07-19 12:22:20 Library/lib/RDKitSmilesParse.dll 
2024-07-19T12:59:08.7722391Z ?rw-rw-rw- 0/0      75264 2024-07-19 12:22:27 Library/lib/RDKitSubgraphs.dll 
2024-07-19T12:59:08.7723504Z ?rw-rw-rw- 0/0     411136 2024-07-19 12:47:26 Library/lib/RDKitSubstructLibrary.dll 
2024-07-19T12:59:08.7724722Z ?rw-rw-rw- 0/0     254976 2024-07-19 12:24:12 Library/lib/RDKitSubstructMatch.dll 
2024-07-19T12:59:08.7725865Z ?rw-rw-rw- 0/0     113664 2024-07-19 12:44:57 Library/lib/RDKitTautomerQuery.dll 
2024-07-19T12:59:08.7726989Z ?rw-rw-rw- 0/0      66048 2024-07-19 12:22:20 Library/lib/RDKitTrajectory.dll 
2024-07-19T12:59:08.7728093Z ?rw-rw-rw- 0/0     448512 2024-07-19 12:15:52 Library/lib/RDKitavalon_clib.dll 
2024-07-19T12:59:08.7729267Z ?rw-rw-rw- 0/0     606208 2024-07-19 12:15:00 Library/lib/RDKitcoordgen.dll 
2024-07-19T12:59:08.7730382Z ?rw-rw-rw- 0/0     131072 2024-07-19 12:15:54 Library/lib/RDKitfreesasa_clib.dll 
2024-07-19T12:59:08.7731942Z ?rw-rw-rw- 0/0      51200 2024-07-19 12:16:00 Library/lib/RDKitga.dll 
2024-07-19T12:59:08.7733023Z ?rw-rw-rw- 0/0      12288 2024-07-19 12:16:04 Library/lib/RDKithc.dll 
2024-07-19T12:59:08.7734444Z ?rw-rw-rw- 0/0     244736 2024-07-19 12:15:48 Library/lib/RDKitmaeparser.dll 
```

I'll update the tests and send a PR.

**Comment by skearnes** [comment]
(@jaimergp this is the second time I've seen issues with the CI/CD pipeline not creating a clean env on Windows)

**Comment by greglandrum** [comment]
It is odd that it worked for me. Wonder what's going on

**Comment by skearnes** [comment]
This might just be a search path issue; copying the `lib/` DLLs might be a red herring:

![Screenshot 2024-08-02 172120](https://github.com/user-attachments/assets/78ed3534-3b18-45cf-b13f-c42f717e9c5e)

**Comment by skearnes** [comment]
@greglandrum I think I know why it works for you on Python 3.12:
![Screenshot 2024-08-02 173150](https://github.com/user-attachments/assets/d05fc36a-629a-4722-960f-1aac319392b3)

**Comment by skearnes** [comment]
The build isn't finding the python library:
```
2024-08-02T18:47:04.1104096Z WARNING (librdkit,Library/bin/RDKitRDBoost.dll): $RPATH/python310.dll not found in packages, sysroot(s) nor the missing_dso_whitelist.
2024-08-02T18:47:04.1105309Z .. is this binary repackaging?
2024-08-02T18:47:04.1958218Z WARNING (librdkit,Library/bin/RDKitRDBoost.dll): $RPATH/boost_python310.dll not found in packages, sysroot(s) nor the missing_dso_whitelist.
2024-08-02T18:47:04.1959462Z .. is this binary repackaging?
```

**Comment by skearnes** [comment]
I think this might be because the linking seems to be happening at package build time, and `librdkit` doesn't have python available. Let me try to address that in #169

**Comment by greglandrum** [comment]
I just checked with a freshly built python 3.10 environment and could reproduce it there. So strange.

**Comment by RMeli** [comment]
Thank you all for looking into this (I was on holidays). Unfortunately I don't have a local Windows machine so I can't reproduce it locally, but it has been failing consistently on [`spyrmsd` GI](https://github.com/RMeli/spyrmsd/actions). I've seen failures with all versions of Python that are tested: [`3.9`](https://github.com/RMeli/spyrmsd/actions/runs/10086122312/job/27888159106), [`3.10`](https://github.com/RMeli/spyrmsd/actions/runs/10171862924/job/28133576027), [`3.11`](https://github.com/RMeli/spyrmsd/actions/runs/10127600480/job/28005592871), and [`3.12`](https://github.com/RMeli/spyrmsd/actions/runs/10103659807/job/27941414853).

**Comment by skearnes** [comment]
@RMeli please try again; #169 appears to have fixed it (https://github.com/conda-forge/rdkit-feedstock/pull/169#issuecomment-2268832170). Sorry for the trouble!
