### ISSUE TITLE
ImportError: DLL load failed: The specified procedure could not be found. 

### ISSUE THREAD

**Issue by mikemhenry** [conda-forge/rdkit-feedstock#97]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

I'm running into an issue when building this package: [recipes/lomap2/meta.yaml](https://github.com/conda-forge/staged-recipes/pull/18154/files#diff-4987410e2f5933539ea87192434c91922a47f2424b55dfb29f64c77cd5884535)
https://github.com/conda-forge/staged-recipes/pull/18154

https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=470731&view=logs&j=240f1fee-52bc-5498-a14a-8361bde76ba0&t=06d62fd2-ab49-5add-9ee5-83b6882d7d2b&l=2292

```
import: 'lomap'
Matplotlib is building the font cache; this may take a moment.
Traceback (most recent call last):
  File "C:\bld\lomap2_1646765357967\test_tmp\run_test.py", line 2, in <module>
    import lomap
  File "C:\bld\lomap2_1646765357967\_test_env\lib\site-packages\lomap\__init__.py", line 62, in <module>
    from .dbmol import DBMolecules
  File "C:\bld\lomap2_1646765357967\_test_env\lib\site-packages\lomap\dbmol.py", line 38, in <module>
    from . import graphgen
  File "C:\bld\lomap2_1646765357967\_test_env\lib\site-packages\lomap\graphgen.py", line 42, in <module>
    from rdkit.Chem import Draw
  File "C:\bld\lomap2_1646765357967\_test_env\lib\site-packages\rdkit\__init__.py", line 2, in <module>
    from .rdBase import rdkitVersion as __version__
ImportError: DLL load failed: The specified procedure could not be found.
```

I'm not sure if there is something wrong with the rdkit windows build on conda-forge or not. The linux and mac builds work okay, but I'm not sure if the windows build will need more pinning or not. 

### Installed packages

```shell
boost:                   1.77.0-py37h457096e_0       conda-forge
    boost-cpp:               1.77.0-h5b4e17d_1           conda-forge
    brotli:                  1.0.9-h8ffe710_6            conda-forge
    brotli-bin:              1.0.9-h8ffe710_6            conda-forge
    bzip2:                   1.0.8-h8ffe710_4            conda-forge
    ca-certificates:         2021.10.8-h5b45459_0        conda-forge
    cairo:                   1.14.12-h20b6c0e_1007       conda-forge
    certifi:                 2021.10.8-py37h03978a9_1    conda-forge
    cycler:                  0.11.0-pyhd8ed1ab_0         conda-forge
    fonttools:               4.29.1-py37hcc03f2d_0       conda-forge
    freetype:                2.10.4-h546665d_1           conda-forge
    icu:                     64.2-he025d50_1             conda-forge
    intel-openmp:            2022.0.0-h57928b3_3663      conda-forge
    jbig:                    2.1-h8d14728_2003           conda-forge
    jpeg:                    9e-h8ffe710_0               conda-forge
    kiwisolver:              1.3.2-py37h8c56517_1        conda-forge
    lcms2:                   2.12-h2a16943_0             conda-forge
    lerc:                    3.0-h0e60522_0              conda-forge
    libblas:                 3.9.0-13_win64_mkl          conda-forge
    libbrotlicommon:         1.0.9-h8ffe710_6            conda-forge
    libbrotlidec:            1.0.9-h8ffe710_6            conda-forge
    libbrotlienc:            1.0.9-h8ffe710_6            conda-forge
    libcblas:                3.9.0-13_win64_mkl          conda-forge
    xorg-libxdmcp:           1.1.3-hcd874cb_0            conda-forge
    xz:                      5.2.5-h62dcd97_1            conda-forge
    zlib:                    1.2.11-h8ffe710_1013        conda-forge
    zstd:                    1.5.2-h6255e5f_0            conda-forge
```

### Environment info

```shell
unknown
```

**Comment by mikemhenry** [comment]
I removed `boost-cpp` from the meta.yaml as a dependency and that fixed the issue, sorry for the noise!
